# Generated by Django 4.1.10 on 2023-11-30 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0002_ahmarmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahmarmodel',
            name='date_joined',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
