# Generated by Django 4.1.10 on 2023-12-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0003_alter_ahmarmodel_date_joined'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AhmarModel',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
