# Generated by Django 4.1.10 on 2023-12-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0008_room_booking_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
