# Generated by Django 4.1.10 on 2023-12-07 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0011_booking_room_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room_number',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='room_type',
        ),
    ]
