# Generated by Django 4.1.10 on 2023-12-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0022_alter_userinfo_address_alter_userinfo_cnic_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='gender',
            new_name='Gender',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='fname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
