# Generated by Django 4.1.10 on 2023-12-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0023_rename_gender_userinfo_gender_userinfo_fname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='cnic_number',
            field=models.IntegerField(max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='issue_date',
            field=models.IntegerField(max_length=19, null=True),
        ),
    ]
