# Generated by Django 4.1.10 on 2023-12-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0024_alter_userinfo_cnic_number_alter_userinfo_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='cnic_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
