# Generated by Django 4.1.10 on 2023-12-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0027_room_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_date',
        ),
        migrations.AddField(
            model_name='payment',
            name='uname',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
