# Generated by Django 4.1.10 on 2023-12-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0031_booking_deduction_amount_booking_is_canceled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='deduction_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
