# Generated by Django 4.1.10 on 2023-12-29 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0032_alter_booking_deduction_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='deduction_amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_canceled',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_paid',
        ),
    ]
