# Generated by Django 4.1.10 on 2023-12-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0033_remove_booking_deduction_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_paid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
