# Generated by Django 4.1.10 on 2023-12-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0034_booking_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='deduction_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_canceled',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
