# Generated by Django 4.1.10 on 2023-11-23 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('checkedIn', 'Checked In'), ('checkedOut', 'Checked Out'), ('breakedIn', 'Breaked In'), ('breakedOut', 'Breaked Out')], default='checkedOut', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userstatus')),
            ],
        ),
    ]
