# Generated by Django 4.1.10 on 2023-11-27 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_profile_status_delete_userstatus_profile_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('checkedin', 'Checked In'), ('checkedout', 'Checked Out'), ('breakedin', 'Breaked In'), ('breakedout', 'Breaked Out')], default='checkedout', max_length=20),
        ),
    ]
