# Generated by Django 4.1.10 on 2023-11-27 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_status_timestamp_alter_status_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='timestamp',
            new_name='timee',
        ),
    ]
