# Generated by Django 4.1.10 on 2023-11-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_status_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='duty_time',
            field=models.DateTimeField(null=True),
        ),
    ]
