# Generated by Django 4.1.10 on 2023-11-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_status_duty_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='name',
        ),
        migrations.AddField(
            model_name='status',
            name='break_time',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='breakedin_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='breakedout_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='checkedin_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='checkedout_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='duty_time',
            field=models.DurationField(null=True),
        ),
    ]
