# Generated by Django 4.1.10 on 2023-11-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_status_name_status_break_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='extra_time',
            field=models.DurationField(null=True),
        ),
    ]
