# Generated by Django 4.1.10 on 2023-11-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_status_extra_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='extra_time',
        ),
        migrations.AlterField(
            model_name='status',
            name='break_time',
            field=models.DateTimeField(null=True),
        ),
    ]
