# Generated by Django 4.1.10 on 2023-11-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_status_extra_time_alter_status_break_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='break_time',
            field=models.DurationField(null=True),
        ),
    ]
